name: playwright tests
on:
  push:
    branches:[main]
  pull_request:
    branches:[main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [demo_qa]
    steps:
      - name: Checkout repository 
        uses: actions/Checkout@v4
      - name: Setup Node.jobs
        uses: actions/Setup-Node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          npx playwright install 
          ENV=qa npx playwright test --project demo_qa